POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inlhc2gxQGdtYWlsLmNvbSIsImV4cCI6MTcyNTgyMjgwNiwidXNlcklkIjo3fQ.8IOUCG9NHq5g7kE8kTpzdIp6zZ2MqWQURWRTKV5TN_E

{
    "name": "Event test only",
    "Description": "This is event only",
    "location": "Location Noida",
    "organizer": "Organizer Manish",
    "startTime": "2025-10-26T15:40:00.00Z"
    
}