POST http://localhost:8080/events
Content-Type: application/json

{
    "name": "Event 5",
    "Description": "This is event 5",
    "location": "Location 5",
    "organizer": "Organizer 5",
    "startTime": "2025-10-26T15:40:00.00Z"
    
}