DELETE  http://localhost:8080/events/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inlhc2gxQGdtYWlsLmNvbSIsImV4cCI6MTcyNTgyMjgwNiwidXNlcklkIjo3fQ.8IOUCG9NHq5g7kE8kTpzdIp6zZ2MqWQURWRTKV5TN_E
